replicaCount: 2

image:
  repository: 861142265676.dkr.ecr.us-east-2.amazonaws.com/devops-app
  tag: c16a1481609c729d0d127e76e2842092a65bbfb2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 5000