replicaCount: 2

image:
  repository: 861142265676.dkr.ecr.us-east-2.amazonaws.com/devops-app
  tag: ff37a47955edaeb361673d6d8dd54121e084426b
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 5000