replicaCount: 2

image:
  repository: 861142265676.dkr.ecr.us-east-2.amazonaws.com/devops-app
  tag: 560f1079e6458446882a7e850777fe7a87428896
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 5000