replicaCount: 2

image:
  repository: 861142265676.dkr.ecr.us-east-2.amazonaws.com/devops-app
  tag: f258f11574b1ce7dde6e0474978b374065d5a572
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 5000