replicaCount: 2

image:
  repository: 861142265676.dkr.ecr.us-east-2.amazonaws.com/devops-app
  tag: 2ed55c184ddc3145bff66cabe46cca65d35ef378
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 5000