replicaCount: 2

image:
  repository: 861142265676.dkr.ecr.us-east-2.amazonaws.com/frontend-app
  tag: 3d8ec1fa1fa51a5e8e94e415728da3101c810b70
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 80