apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: frontend-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/jatindeshpande/gitops.git
    targetRevision: HEAD
    path: helm/devops-app/templates/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true